- name: "SEPP SSH Prototype Group"
  members:
    - "2558689"
    - "2555422"
    - "2611951"
    - "2584182"
  id: 189660
- name: "HESS - Assigned Group 1"
  members:
    - "2720963"
    - "2578602"
    - "2456077"
  id: 189395
- name: "SSH - Assigned Group 1"
  members:
    - "2598190"
    - "2551575"
    - "2595798"
    - "2879666"
  id: 189396
- name: "SSH - Assigned Group 2"
  members:
    - "2617364"
    - "2565185"
    - "2616477"
    - "2707500"
  id: 189398
- name: "Untitled group"
  members:
    - "2308934"
    - "2547788"
    - "2509095"
    - "2553338"
  id: 189499
- name: "Our House"
  members:
    - "2561359"
    - "2555273"
    - "2559809"
  id: 189606
- name: "HESS - CSRS - Automarker (Amongsus)"
  members:
    - "2566797"
    - "2600866"
    - "2586419"
    - "2648065"
  id: 189604
- name: "John Team"
  members:
    - "2583378"
    - "2612509"
    - "2593423"
    - "2277898"
  id: 189602
- name: "HouseHuddle"
  members:
    - "2587224"
    - "2553571"
    - "2616092"
    - "2629238"
- name: "SSH - A,E,L,M"
  members:
    - "2582826"
    - "2616316"
    - "2558630"
    - "2562101"
  id: 189659
