- name: "alt+255"
  members:
    - "2615984"
    - "2448622"
    - "2611580"
    - "2451083"
  id: 189746
- name: "SEPP SSH Prototype Group"
  members:
    - "2558689"
    - "2555422"
    - "2611951"
    - "2584182"
  id: 189660
- name: "HESS - Assigned Group 1"
  members:
    - "2720963"
    - "2578602"
    - "2456077"
    - "2620745"
  id: 189395
- name: "SSH - Assigned Group 1"
  members:
    - "2598190"
    - "2551575"
    - "2595798"
    - "2879666"
  id: 189396
- name: "SSH - Assigned Group 2"
  members:
    - "2617364"
    - "2565185"
    - "2616477"
    - "2707500"
  id: 189398
- name: "SSH - Assigned Group 3"
  members:
    - "2308934"
    - "2547788"
    - "2509095"
    - "2553338"
  id: 189499
- name: "SSHiverMeTimbers"
  members:
    - "2585019"
    - "2619820"
    - "2614348"
    - "2567906"
  id: 189913
- name: "Group SM"
  members:
    - "2601585"
    - "2554198"
    - "2551161"
    - "2627621"
  id: 189912
- name: "Our House"
  members:
    - "2561359"
    - "2555273"
    - "2559809"
  id: 189606
- name: "HESS - CSRS - Automarker (Amongsus)"
  members:
    - "2566797"
    - "2600866"
    - "2586419"
    - "2648065"
  id: 189604
- name: "John Team"
  members:
    - "2583378"
    - "2612509"
    - "2593423"
    - "2277898"
  id: 189602
- name: "dahir party"
  members:
    - "2586348"
    - "2610945"
    - "2467516"
    - "2628595"
  id: 189744
- name: "HouseHuddle"
  members:
    - "2587224"
    - "2553571"
    - "2616092"
    - "2629238"
  id: 189743
- name: "SSH - A,E,L,M"
  members:
    - "2582826"
    - "2616316"
    - "2558630"
    - "2562101"
  id: 189659
- name: "SSH-AGIS"
  members:
    - "2596966"
    - "2614405"
    - "2607016"
    - "2616327"
  id: 189747
- name: "SSH - L, W, K"
  members:
    - "2565112"
    - "2558491"
    - "2587108"
  id: 189745
- name: "SSH - Assigned Group 4"
  members:
    - "2448654"
    - "2644345"
    - "2475559"
  id: 189748
- name: "SSH - Assigned Group 5"
  members:
    - "2582538"
    - "2666525"
    - "2328859"
  id: 189749
- name: "SSH - Rowan, Lucas, Jack, Ethan"
  members:
    - "2580242"
    - "2560031"
    - "2599496"
    - "2569881"
- name: "SSH - group project"
  members:
    - "2561952"
    - "2644336"
    - "2627872"
    - "2616345"
  id: 189919
- name: "SSH - A, Z, D"
  members:
    - "2448049"
    - "2448130"
    - "2559680"
  id: 189918
- name: "SSH - UGM cabang Depok"
  members:
    - "2805117"
    - "2818750"
    - "2805454"
  id: 189917
- name: "SSH - prototype1.jpg"
  members:
    - "2603883"
    - "2602085"
    - "2673835"
    - "2515401"
  id: 189916
- name: "HESS - くコ:彡group"
  members:
    - "2588313"
    - "2607291"
    - "2605039"
  id: 189914
