- name: "HESS - Assigned Group 1"
  members:
    - "2720963"
    - "2578602"
    - "2456077"
  id: 189395
- name: "SSH - Assigned Group 1"
  members:
    - "2598190"
    - "2551575"
    - "2595798"
    - "2879666"
  id: 189396
- name: "SSH - Assigned Group 2"
  members:
    - "2617364"
    - "2565185"
    - "2616477"
    - "2707500"
  id: 189398
- name: "Untitled group"
  members:
    - "2308934"
    - "2547788"
    - "2509095"
    - "2553338"
  id: 189499
- name: "John Team"
  members:
    - "2583378"
    - "2612509"
    - "2593423"
    - "2277898"
