name: "Prototype Groups"
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'

    permissions:
      contents: read
      actions: read
      issues: write
      pull-requests: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Compile TypeScript sources
        uses: ./.github/actions/build

      - name: Delete existing groups.yaml
        run: |
          echo "${{ toJson(github.event.workflow_run) }}"
          rm ./config/groups.yaml

      - name: Download PR artifact
        uses: actions/download-artifact@v4
        with:
          name: groups.yaml
          path: ./config/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format groups.yaml
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add config/groups.yaml
          git commit -m 'Temporary commit'
          npm run format-config

      - name: Check for changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ ! -z "$(git status --porcelain)" ]; then
            echo \
              'Running \`npm run format-config\` changed the formatting of \`groups.yaml\`:\n\n\`\`\`diff\n' \
              "$(git diff)\n" \
              '\`\`\`\n\nPlease run \`npm run format-config\` locally and commit the changes.' | gh pr comment --body-file - ${{ github.event.workflow_run.pull_requests[0].number }}
          fi

      - name: Validate configuration
        run: npm run validate
        env:
          CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}

      - name: "Post changes as PR comment"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let fs = require('fs');
            let markdown = 'changes.md';
            let issue_number = Number(fs.readFileSync('pr.yaml', 'utf-8'));

            if (fs.existsSync(markdown)) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: fs.readFileSync('changes.md', 'utf-8')
              });
            }

  apply:
    name: "Apply"
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' && github.ref == 'refs/heads/main'

    concurrency:
      group: "canvas-update"
      cancel-in-progress: false

    permissions:
      contents: write

    steps:
      - name: Get token for sepp-bot
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.SEPP_BOT_ID }}
          private-key: ${{ secrets.SEPP_BOT_PK }}

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Compile TypeScript sources
        uses: ./.github/actions/build

      - name: "Apply changes"
        run: npm run apply
        env:
          CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}

      - name: Format group configuration file
        run: npm run format-config

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Check for changes and commit them
        run: |
          if [ ! -z "$(git status --porcelain)" ]; then
            git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
            git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
            git add ./config/groups.yaml
            git commit -m "Update configuration with Canvas IDs"
            git push -u origin "HEAD:${{ github.ref }}"
          fi
